import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import AuthSession from './AuthSession';
import LeftMenu from './_components/LeftMenu';

import './globals.css';
import './sb-admin-2.css';
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Alcohol Friday Admin',
    default: 'Alcohol Friday Admin',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body style={{ display: 'flex' }}>
        {/* <AuthSession> */}
        <LeftMenu />
        {children}
        {/* </AuthSession> */}
      </body>
    </html>
  );
}
