import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NextUIProviders } from './providers';
import ReactQueryProvider from './_hooks/useReactQuery';
import Header from './_components/Header';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Alcohol Friday Admin',
    default: 'Alcohol Friday Admin',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="light">
      <body className={inter.className}>
        {/* <div id="__next"> */}
        <NextUIProviders>
          <ReactQueryProvider>
            <Header />
            {children}
          </ReactQueryProvider>
        </NextUIProviders>
        {/* </div> */}
      </body>
    </html>
  );
}
