import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './sb-admin-2.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import AuthSession from './AuthSession';
import LeftMenu from './_components/LeftMenu';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthSession>
          <LeftMenu>{children}</LeftMenu>
        </AuthSession>
      </body>
    </html>
  );
}
